version: '2'
services:
  nginx:
    build: .
    ports:
     - "80:8080"
    volumes:
        #- ./tmp/:/test/:ro
        #- ./src/default.conf:/etc/nginx/conf.d/default.conf
        - ./repo/:/repo/:rw
        #- ./bin/:/repo/
  
